/**
 * Generate the rules engine's schema-derived sources from the vendored standard:
 *
 *   src/generated/validate-request.ts   the request schema (FS-RULES-001), the pack schema
 *   src/generated/validate-pack.ts      (FS-RULES-004), the profile schema (FS-RULES-002) and the
 *   src/generated/validate-profile.ts   report schema (what every report the engine returns is
 *   src/generated/validate-report.ts    tested against), each as standalone ajv code: no
 *                                       `new Function` at runtime, so it runs under a strict CSP
 *                                       in the browser, exactly as the engine's validators do
 *   src/generated/types.ts              TypeScript types for a request, pack, rule, profile and
 *                                       report (FLR-ADR-006: the schema is the source)
 *   src/generated/extension-defaults.ts the defaults each official extension's schema gives the
 *                                       members of its elements and records (Rules 4.5), from the
 *                                       engine's vendored registry — the extension versions the
 *                                       engine implements
 *
 *   pnpm --filter @floorspec/rules-engine generate          write them
 *   pnpm --filter @floorspec/rules-engine check:generated   fail if writing them would change anything
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
const standaloneCode = standalone.default;
import { compile } from 'json-schema-to-typescript';

const here = dirname(new URL(import.meta.url).pathname);
const root = resolve(here, '..');
const schemaDir = join(root, 'standard', 'schema', 'rules', '0.1');
const registryDir = join(root, '..', 'engine', 'standard', 'registry');
const outDir = join(root, 'src', 'generated');

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

const HEADER = (from: string, what: string): string =>
  `// GENERATED by packages/rules-engine/scripts/generate.ts from ${from} — do not edit.\n// ${what}\n`;

function loadFiles(): Map<string, JsonObject> {
  if (!existsSync(schemaDir)) throw new Error(`${schemaDir} does not exist; run sync-standard first`);
  const files = new Map<string, JsonObject>();
  for (const f of readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json')).sort())
    files.set(f.replace(/\.schema\.json$/, ''), JSON.parse(readFileSync(join(schemaDir, f), 'utf8')) as JsonObject);
  return files;
}

const INSTANCE_KEYWORDS = new Set(['const', 'enum', 'default', 'examples']);
const MAP_KEYWORDS = new Set(['properties', 'patternProperties', '$defs', 'dependentSchemas']);

/** Bundle the files into one schema rooted at `rootName`, every `$ref` rewritten inside it (as packages/engine/scripts/generate.ts). */
function bundle(files: Map<string, JsonObject>, rootName: string | null): JsonObject {
  const rewrite = (node: Json, file: string, isMap: boolean): Json => {
    if (Array.isArray(node)) return node.map((n) => rewrite(n, file, false));
    if (node === null || typeof node !== 'object') return node;
    const out: JsonObject = {};
    for (const [k, v] of Object.entries(node)) {
      if (!isMap && (k === '$schema' || k === '$id')) continue;
      if (!isMap && k === '$ref' && typeof v === 'string') {
        const [target, frag = ''] = v.split('#') as [string, string?];
        const name = target === '' ? file : target.replace(/\.schema\.json$/, '');
        if (!files.has(name)) throw new Error(`${file}: $ref ${v} names no schema file`);
        out[k] = `#/$defs/${name}${frag}`;
      } else if (!isMap && INSTANCE_KEYWORDS.has(k)) {
        out[k] = v;
      } else {
        out[k] = rewrite(v, file, !isMap && MAP_KEYWORDS.has(k));
      }
    }
    return out;
  };
  const defs: JsonObject = {};
  for (const [name, schema] of files) defs[name] = rewrite(schema, name, false);
  if (rootName === null) return { $schema: 'https://json-schema.org/draft/2020-12/schema', $defs: defs };
  const rootSchema = files.get(rootName);
  if (!rootSchema) throw new Error(`${rootName}.schema.json is missing`);
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: (rootSchema.$id as string).replace(/\.schema\.json$/, '.bundle.json'),
    $ref: `#/$defs/${rootName}`,
    $defs: defs,
  };
}

/** Runtime helpers ajv's standalone code `require`s, inlined so the package has no runtime deps. */
const UCS2LENGTH = `function ucs2length(str) {
  // The length of a string in Unicode code points.
  let length = 0;
  let pos = 0;
  const len = str.length;
  while (pos < len) {
    length++;
    const value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      const next = str.charCodeAt(pos);
      if ((next & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
}`;
const EQUAL = `function equal(a, b) {
  // Deep equality of JSON values (ajv's runtime/equal, which is fast-deep-equal).
  if (a === b) return true;
  if (a && b && typeof a == "object" && typeof b == "object") {
    if (Array.isArray(a) !== Array.isArray(b)) return false;
    if (Array.isArray(a)) {
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) if (!equal(a[i], b[i])) return false;
      return true;
    }
    const keys = Object.keys(a);
    if (keys.length !== Object.keys(b).length) return false;
    for (const k of keys) if (!Object.prototype.hasOwnProperty.call(b, k) || !equal(a[k], b[k])) return false;
    return true;
  }
  return a !== a && b !== b;
}`;

function validatorSource(schema: JsonObject, from: string, what: string): string {
  // The engine's options (packages/engine/scripts/generate.ts): `format` is an annotation; the
  // `pattern` beside an https URI is what every validator checks.
  const ajv = new Ajv2020({
    strict: true,
    strictRequired: false,
    allErrors: false,
    validateFormats: false,
    code: { source: true, esm: true, lines: true },
  });
  const validate = ajv.compile(schema);
  let code = standaloneCode(ajv, validate);
  const helpers: string[] = [];
  code = code.replace(/const (\w+) = require\("ajv\/dist\/runtime\/(\w+)"\)\.default;?/g, (_m, local: string, mod: string) => {
    if (mod === 'ucs2length') helpers.push(UCS2LENGTH.replace('function ucs2length', `function ${local}`));
    else if (mod === 'equal') helpers.push(EQUAL.replace(/equal\(/g, `${local}(`));
    else throw new Error(`standalone code requires ajv/dist/runtime/${mod}, which generate.ts does not inline`);
    return '';
  });
  if (/require\(/.test(code)) throw new Error('standalone code still requires a module');
  if (/new Function|eval\(/.test(code)) throw new Error('standalone code evaluates code at runtime');
  return (
    HEADER(from, `${what}, compiled by ajv to standalone code: no code is evaluated at runtime.`) +
    '// @ts-nocheck\n/* eslint-disable */\n' +
    helpers.join('\n') +
    '\n' +
    code.trim() +
    '\n'
  );
}

async function typesSource(files: Map<string, JsonObject>): Promise<string> {
  const all = bundle(files, null);
  // One root that names each top-level object, so every shared definition is emitted once.
  const schema: JsonObject = {
    ...all,
    title: 'Rules schemas',
    type: 'object',
    properties: {
      request: { $ref: '#/$defs/request' },
      pack: { $ref: '#/$defs/pack' },
      rule: { $ref: '#/$defs/rule' },
      profile: { $ref: '#/$defs/profile' },
      report: { $ref: '#/$defs/report' },
      finding: { $ref: '#/$defs/finding' },
    },
    additionalProperties: false,
  };
  const ts = await compile(schema, 'RulesSchemas', {
    bannerComment: '',
    additionalProperties: false,
    unreachableDefinitions: false,
    strictIndexSignatures: true,
    format: true,
    style: { singleQuote: true, printWidth: 120 },
  });
  return (
    HEADER('standard/schema/rules/0.1', 'TypeScript types for the Rules 0.1 objects, generated from the schemas with json-schema-to-typescript.') +
    '/* eslint-disable */\n' +
    ts
  );
}

/**
 * 4.5: the defaults each official extension's schema gives its elements' and records' members —
 * `collections.<c>` and every other top-level map (circuits, stacks, gas sources) whose members are
 * `#/$defs/<x>` — read as the oracle reads them: the `default` of each property of that definition.
 */
function extensionDefaults(): string {
  if (!existsSync(registryDir)) throw new Error(`${registryDir} does not exist; run the engine's sync-standard first`);
  const elements: Record<string, Record<string, Record<string, Json>>> = {};
  const records: Record<string, Record<string, Record<string, Json>>> = {};
  for (const name of readdirSync(registryDir).sort()) {
    if (!name.startsWith('FS_') || !existsSync(join(registryDir, name, 'extension.json'))) continue;
    const entry = JSON.parse(readFileSync(join(registryDir, name, 'extension.json'), 'utf8')) as { schema: string };
    const schema = readdirSync(join(registryDir, name))
      .filter((f) => f.endsWith('.schema.json'))
      .map((f) => JSON.parse(readFileSync(join(registryDir, name, f), 'utf8')) as JsonObject)
      .find((s) => s.$id === entry.schema);
    if (!schema) throw new Error(`registry/${name}: no schema has the $id ${entry.schema}`);
    const defs = (schema.$defs ?? {}) as Record<string, JsonObject>;
    const defaultsOf = (holder: Json | undefined): Record<string, Json> => {
      const ap = holder !== null && typeof holder === 'object' && !Array.isArray(holder) ? holder.additionalProperties : undefined;
      const ref = ap !== null && typeof ap === 'object' && !Array.isArray(ap) && typeof ap.$ref === 'string' ? ap.$ref : '';
      if (!ref.startsWith('#/$defs/')) return {};
      const props = (defs[ref.slice('#/$defs/'.length)]?.properties ?? {}) as Record<string, JsonObject>;
      const out: Record<string, Json> = {};
      for (const k of Object.keys(props).sort()) if ('default' in props[k]!) out[k] = props[k].default!;
      return out;
    };
    const top = (schema.properties ?? {}) as Record<string, JsonObject>;
    const colls = ((top.collections?.properties ?? {}) as Record<string, JsonObject>);
    elements[name] = {};
    for (const c of Object.keys(colls).sort()) elements[name][c] = defaultsOf(colls[c]);
    records[name] = {};
    for (const k of Object.keys(top).sort()) if (k !== 'collections') records[name][k] = defaultsOf(top[k]);
  }
  return (
    HEADER('../engine/standard/registry', 'The defaults the official extensions give the members of their elements and records (Rules 4.5).') +
    `export const ELEMENT_DEFAULTS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, unknown>>>>>> = ${JSON.stringify(elements, null, 2)};\n\n` +
    `export const RECORD_DEFAULTS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, unknown>>>>>> = ${JSON.stringify(records, null, 2)};\n`
  );
}

export async function generate(): Promise<Map<string, string>> {
  const files = loadFiles();
  const out = new Map<string, string>();
  for (const [name, what] of [
    ['request', 'The evaluation request schema (Rules 1.1; FS-RULES-001)'],
    ['pack', 'The rule pack schema (Rules 2.1, 3; FS-RULES-004)'],
    ['profile', 'The jurisdiction profile schema (Rules 10.1; FS-RULES-002)'],
    ['report', 'The report schema (Rules 9.1)'],
  ] as const)
    out.set(`validate-${name}.ts`, validatorSource(bundle(files, name), `standard/schema/rules/0.1/${name}.schema.json`, what));
  out.set('types.ts', await typesSource(files));
  out.set('extension-defaults.ts', extensionDefaults());
  return out;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const out = await generate();
  let stale = 0;
  for (const [name, text] of out) {
    const path = join(outDir, name);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
    if (current === text) continue;
    if (check) {
      console.error(`check:generated: src/generated/${name} is out of date — run \`pnpm --filter @floorspec/rules-engine generate\``);
      stale++;
    } else {
      writeFileSync(path, text);
      console.log(`generate: wrote src/generated/${name}`);
    }
  }
  if (stale) process.exit(1);
  if (check) console.log('check:generated: src/generated is up to date');
}

await main();
