/**
 * Generate the engine's schema-derived sources from the vendored standard:
 *
 *   src/generated/schema.ts            the Core 0.2 schema files bundled into one self-contained
 *                                      schema, as data — the canonicalizer's table of constant
 *                                      defaults (9.2 step 1), which serves 0.1 documents too
 *   src/generated/validate-0.1.ts      the schema tier (FS-SCH-001) of each draft as standalone ajv
 *   src/generated/validate-0.2.ts      code: no `new Function` at runtime, so it runs under a strict
 *                                      CSP in the browser. A 0.2 reader applies 0.1's schema to a
 *                                      document that declares "0.1" (FS-CORE-1.2.4)
 *   src/generated/validate-registry.ts the registry entry schema (Core 0.2, 12.2), for FS-CFG-001
 *   src/generated/types.ts             TypeScript types for a Core 0.2 document (FLR-T-1.5,
 *                                      FLR-ADR-006: the schema is the source; the types are
 *                                      generated from it)
 *   src/generated/registry-types.ts    and for a registry entry
 *   src/generated/official-extensions.ts   the official extensions' registry entries and schemas, as data
 *   src/generated/validate-FS_<x>.ts       each official extension's schema (FS-<CODE>-SCH-001),
 *                                          as standalone ajv code
 *   src/generated/types-FS_<x>.ts          and TypeScript types for its top-level data
 *
 *   pnpm --filter @floorspec/engine generate          write them
 *   pnpm --filter @floorspec/engine check:generated   fail if writing them would change anything
 */
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
const standaloneCode = standalone.default;
import { compile } from 'json-schema-to-typescript';

const here = dirname(new URL(import.meta.url).pathname);
const engineRoot = resolve(here, '..');
const schemaRoot = join(engineRoot, 'standard', 'schema');
const outDir = join(engineRoot, 'src', 'generated');

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

const HEADER = (from: string, what: string) =>
  `// GENERATED by packages/engine/scripts/generate.ts from standard/schema/${from} — do not edit.\n// ${what}\n`;

/** The files' short names: `wall.schema.json` → `wall`. */
function loadFiles(sub: string): Map<string, JsonObject> {
  const schemaDir = join(schemaRoot, sub);
  if (!existsSync(schemaDir)) throw new Error(`${schemaDir} does not exist; run sync-standard first`);
  const files = new Map<string, JsonObject>();
  for (const f of readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json')).sort())
    files.set(f.replace(/\.schema\.json$/, ''), JSON.parse(readFileSync(join(schemaDir, f), 'utf8')) as JsonObject);
  return files;
}

const INSTANCE_KEYWORDS = new Set(['const', 'enum', 'default', 'examples']);
const MAP_KEYWORDS = new Set(['properties', 'patternProperties', '$defs', 'dependentSchemas']);

/**
 * Bundle the files into one schema: each file becomes `#/$defs/<name>`, and every `$ref` — local
 * (`#/$defs/x`, `#`) or to another file (`defs.schema.json#/$defs/id`) — is rewritten to point
 * inside the bundle. Nothing is fetched, so the bundle needs no resolver.
 */
function bundle(files: Map<string, JsonObject>, rootName: string): JsonObject {
  const rewrite = (node: Json, file: string, isMap: boolean): Json => {
    if (Array.isArray(node)) return node.map((n) => rewrite(n, file, false));
    if (node === null || typeof node !== 'object') return node;
    const out: JsonObject = {};
    for (const [k, v] of Object.entries(node)) {
      if (!isMap && (k === '$schema' || k === '$id')) continue;
      if (!isMap && k === '$ref' && typeof v === 'string') {
        const [target, frag = ''] = v.split('#') as [string, string?];
        const name = target === '' ? file : target.replace(/\.schema\.json$/, '');
        if (!files.has(name)) throw new Error(`${file}: $ref ${v} names no schema file`);
        out[k] = `#/$defs/${name}${frag}`;
      } else if (!isMap && INSTANCE_KEYWORDS.has(k)) {
        out[k] = v;
      } else {
        out[k] = rewrite(v, file, !isMap && MAP_KEYWORDS.has(k));
      }
    }
    return out;
  };
  const defs: JsonObject = {};
  for (const [name, schema] of files) defs[name] = rewrite(schema, name, false);
  const root = files.get(rootName);
  if (!root) throw new Error(`${rootName}.schema.json is missing`);
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: (root.$id as string).replace(/\.schema\.json$/, '.bundle.json'),
    $ref: `#/$defs/${rootName}`,
    $defs: defs,
  };
}

/** Runtime helpers ajv's standalone code `require`s, inlined so the engine has no runtime deps. */
const UCS2LENGTH = `function ucs2length(str) {
  // The length of a string in Unicode code points (1.4: "measured in Unicode code points").
  let length = 0;
  let pos = 0;
  const len = str.length;
  while (pos < len) {
    length++;
    const value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      const next = str.charCodeAt(pos);
      if ((next & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
}`;
const EQUAL = `function equal(a, b) {
  // Deep equality of JSON values (ajv's runtime/equal, which is fast-deep-equal).
  if (a === b) return true;
  if (a && b && typeof a == "object" && typeof b == "object") {
    if (Array.isArray(a) !== Array.isArray(b)) return false;
    if (Array.isArray(a)) {
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) if (!equal(a[i], b[i])) return false;
      return true;
    }
    const keys = Object.keys(a);
    if (keys.length !== Object.keys(b).length) return false;
    for (const k of keys) if (!Object.prototype.hasOwnProperty.call(b, k) || !equal(a[k], b[k])) return false;
    return true;
  }
  return a !== a && b !== b;
}`;

function validatorSource(schema: JsonObject, from: string, what: string): string {
  // The same options floorspec's own schema check uses (tools/schema.ts), except formats: in JSON
  // Schema 2020-12 `format` is an annotation, and the `pattern` beside the asset's `uri` is what
  // every validator checks (schema/core/README.md).
  const ajv = new Ajv2020({
    strict: true,
    strictRequired: false,
    allErrors: true,
    validateFormats: false,
    code: { source: true, esm: true, lines: true },
  });
  const validate = ajv.compile(schema);
  let code = standaloneCode(ajv, validate);
  const helpers: string[] = [];
  code = code.replace(/const (\w+) = require\("ajv\/dist\/runtime\/(\w+)"\)\.default;?/g, (_m, local: string, mod: string) => {
    if (mod === 'ucs2length') helpers.push(UCS2LENGTH.replace('function ucs2length', `function ${local}`));
    else if (mod === 'equal') helpers.push(EQUAL.replace(/equal\(/g, `${local}(`));
    else throw new Error(`standalone code requires ajv/dist/runtime/${mod}, which generate.ts does not inline`);
    return '';
  });
  if (/require\(/.test(code)) throw new Error('standalone code still requires a module');
  if (/new Function|eval\(/.test(code)) throw new Error('standalone code evaluates code at runtime');
  return (
    HEADER(from, `${what}, compiled by ajv to standalone code: no code is evaluated at runtime.`) +
    '// @ts-nocheck\n/* eslint-disable */\n' +
    helpers.join('\n') +
    '\n' +
    code.trim() +
    '\n'
  );
}

async function typesSource(schema: JsonObject, name: string, from: string, what: string): Promise<string> {
  const ts = await compile(structuredClone(schema), name, {
    bannerComment: '',
    additionalProperties: false,
    unreachableDefinitions: false,
    strictIndexSignatures: true,
    format: true,
    style: { singleQuote: true, printWidth: 120 },
  });
  return HEADER(from, what) + '/* eslint-disable */\n' + ts;
}

/**
 * The official extensions vendored from the registry (standard/registry/<NAME>/): each one's entry
 * and its schema — the file whose `$id` is the entry's `schema` URL.
 */
type Entry = JsonObject & { name: string; version: string; schema: string };

function officialExtensions(): { name: string; entry: Entry; schema: JsonObject }[] {
  const dir = join(engineRoot, 'standard', 'registry');
  if (!existsSync(dir)) throw new Error(`${dir} does not exist; run sync-standard first`);
  const out: { name: string; entry: Entry; schema: JsonObject }[] = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.startsWith('FS_') || !existsSync(join(dir, name, 'extension.json'))) continue;
    const entry = JSON.parse(readFileSync(join(dir, name, 'extension.json'), 'utf8')) as Entry;
    const schemas = readdirSync(join(dir, name))
      .filter((f) => f.endsWith('.schema.json'))
      .map((f) => JSON.parse(readFileSync(join(dir, name, f), 'utf8')) as JsonObject);
    const schema = schemas.find((x) => x.$id === entry.schema);
    if (!schema) throw new Error(`registry/${name}: no schema has the $id ${entry.schema}`);
    out.push({ name, entry, schema });
  }
  return out;
}

/** Files this script once wrote and no longer does: removed by `generate`, reported by `--check`. */
const RETIRED = ['validate.ts'];

export async function generate(): Promise<Map<string, string>> {
  const core01 = bundle(loadFiles('core/0.1'), 'floorspec');
  const core02 = bundle(loadFiles('core/0.2'), 'floorspec');
  const registry = bundle(loadFiles('registry/0.1'), 'extension');
  const out = new Map<string, string>();
  out.set(
    'schema.ts',
    HEADER('core/0.2', 'The Core 0.2 schema files bundled into one schema. Its `default` keywords are the constant defaults of 9.2 step 1.') +
      `export const SCHEMA = ${JSON.stringify(core02, null, 2)} as const;\n`,
  );
  out.set('validate-0.1.ts', validatorSource(core01, 'core/0.1', 'The Core 0.1 schema tier (FS-SCH-001)'));
  out.set('validate-0.2.ts', validatorSource(core02, 'core/0.2', 'The Core 0.2 schema tier (FS-SCH-001)'));
  out.set('validate-registry.ts', validatorSource(registry, 'registry/0.1', 'The registry entry schema (Core 0.2, 12.2.1; FS-CFG-001)'));
  out.set('types.ts', await typesSource(core02, 'FloorspecDocument', 'core/0.2', 'TypeScript types for a Core 0.2 document, generated from the schema with json-schema-to-typescript.'));
  out.set(
    'registry-types.ts',
    await typesSource(registry, 'RegistryEntry', 'registry/0.1', 'TypeScript types for a registry entry (Core 0.2, 12.2), generated from the schema with json-schema-to-typescript.'),
  );
  // The official extensions (FS_electrical, FS_plumbing, FS_mechanical, FS_lowvoltage): their
  // registry entries as data, each one's schema as a standalone validator (its FS-<CODE>-SCH-001)
  // and as TypeScript types.
  const exts = officialExtensions();
  out.set(
    'official-extensions.ts',
    HEADER('../registry', 'The official extensions\' registry entries (registry/<NAME>/extension.json), as data.') +
      `export const OFFICIAL_ENTRIES = ${JSON.stringify(exts.map((x) => x.entry), null, 2)} as const;\n\n` +
      '// Each one\'s schema, by name: what an editor reads to know a kind\'s members, their types and defaults.\n' +
      `export const OFFICIAL_SCHEMAS = ${JSON.stringify(Object.fromEntries(exts.map((x) => [x.name, x.schema])), null, 2)} as const;\n`,
  );
  for (const x of exts) {
    const schema = { ...x.schema };
    delete schema.$id;
    out.set(`validate-${x.name}.ts`, validatorSource(schema, `../registry/${x.name}`, `The ${x.name} ${x.entry.version} schema`));
    out.set(
      `types-${x.name}.ts`,
      await typesSource(x.schema, `${x.name.replace(/^FS_/, '').replace(/^./, (c) => c.toUpperCase())}Data`, `../registry/${x.name}`,
        `TypeScript types for ${x.name} ${x.entry.version}'s top-level data, generated from its schema with json-schema-to-typescript.`),
    );
  }
  return out;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const out = await generate();
  let stale = 0;
  for (const [name, text] of out) {
    const path = join(outDir, name);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
    if (current === text) continue;
    if (check) {
      console.error(`check:generated: src/generated/${name} is out of date — run \`pnpm --filter @floorspec/engine generate\``);
      stale++;
    } else {
      writeFileSync(path, text);
      console.log(`generate: wrote src/generated/${name}`);
    }
  }
  for (const name of RETIRED) {
    const path = join(outDir, name);
    if (!existsSync(path)) continue;
    if (check) {
      console.error(`check:generated: src/generated/${name} is no longer generated — run \`pnpm --filter @floorspec/engine generate\``);
      stale++;
    } else {
      rmSync(path);
      console.log(`generate: removed src/generated/${name}`);
    }
  }
  if (stale) process.exit(1);
  if (check) console.log('check:generated: src/generated is up to date');
}

await main();
