/**
 * Generate the engine's schema-derived sources from the vendored standard (standard/schema/core/0.1):
 *
 *   src/generated/schema.ts     the schema files bundled into one self-contained schema, as data —
 *                               the canonicalizer's table of constant defaults (9.2 step 1)
 *   src/generated/validate.ts   the schema tier (FS-SCH-001) as standalone ajv code: no `new
 *                               Function` at runtime, so it runs under a strict CSP in the browser
 *   src/generated/types.ts      TypeScript types for the document (FLR-T-1.5, FLR-ADR-006: the
 *                               schema is the source; the types are generated from it)
 *
 *   pnpm --filter @floorspec/engine generate          write them
 *   pnpm --filter @floorspec/engine check:generated   fail if writing them would change anything
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standalone from 'ajv/dist/standalone/index.js';
const standaloneCode = standalone.default;
import { compile } from 'json-schema-to-typescript';

const here = dirname(new URL(import.meta.url).pathname);
const engineRoot = resolve(here, '..');
const schemaDir = join(engineRoot, 'standard', 'schema', 'core', '0.1');
const outDir = join(engineRoot, 'src', 'generated');

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

const HEADER = (what: string) =>
  `// GENERATED by packages/engine/scripts/generate.ts from standard/schema/core/0.1 — do not edit.\n// ${what}\n`;

/** The files' short names: `wall.schema.json` → `wall`. */
function loadFiles(): Map<string, JsonObject> {
  if (!existsSync(schemaDir)) throw new Error(`${schemaDir} does not exist; run sync-standard first`);
  const files = new Map<string, JsonObject>();
  for (const f of readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json')).sort())
    files.set(f.replace(/\.schema\.json$/, ''), JSON.parse(readFileSync(join(schemaDir, f), 'utf8')) as JsonObject);
  return files;
}

const INSTANCE_KEYWORDS = new Set(['const', 'enum', 'default', 'examples']);
const MAP_KEYWORDS = new Set(['properties', 'patternProperties', '$defs', 'dependentSchemas']);

/**
 * Bundle the files into one schema: each file becomes `#/$defs/<name>`, and every `$ref` — local
 * (`#/$defs/x`, `#`) or to another file (`defs.schema.json#/$defs/id`) — is rewritten to point
 * inside the bundle. Nothing is fetched, so the bundle needs no resolver.
 */
function bundle(files: Map<string, JsonObject>): JsonObject {
  const rewrite = (node: Json, file: string, isMap: boolean): Json => {
    if (Array.isArray(node)) return node.map((n) => rewrite(n, file, false));
    if (node === null || typeof node !== 'object') return node;
    const out: JsonObject = {};
    for (const [k, v] of Object.entries(node)) {
      if (!isMap && (k === '$schema' || k === '$id')) continue;
      if (!isMap && k === '$ref' && typeof v === 'string') {
        const [target, frag = ''] = v.split('#') as [string, string?];
        const name = target === '' ? file : target.replace(/\.schema\.json$/, '');
        if (!files.has(name)) throw new Error(`${file}: $ref ${v} names no schema file`);
        out[k] = `#/$defs/${name}${frag}`;
      } else if (!isMap && INSTANCE_KEYWORDS.has(k)) {
        out[k] = v;
      } else {
        out[k] = rewrite(v, file, !isMap && MAP_KEYWORDS.has(k));
      }
    }
    return out;
  };
  const defs: JsonObject = {};
  for (const [name, schema] of files) defs[name] = rewrite(schema, name, false);
  const root = files.get('floorspec');
  if (!root) throw new Error('floorspec.schema.json is missing');
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: (root.$id as string).replace(/floorspec\.schema\.json$/, 'floorspec.bundle.json'),
    $ref: '#/$defs/floorspec',
    $defs: defs,
  };
}

/** Runtime helpers ajv's standalone code `require`s, inlined so the engine has no runtime deps. */
const UCS2LENGTH = `function ucs2length(str) {
  // The length of a string in Unicode code points (1.4: "measured in Unicode code points").
  let length = 0;
  let pos = 0;
  const len = str.length;
  while (pos < len) {
    length++;
    const value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      const next = str.charCodeAt(pos);
      if ((next & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
}`;
const EQUAL = `function equal(a, b) {
  // Deep equality of JSON values (ajv's runtime/equal, which is fast-deep-equal).
  if (a === b) return true;
  if (a && b && typeof a == "object" && typeof b == "object") {
    if (Array.isArray(a) !== Array.isArray(b)) return false;
    if (Array.isArray(a)) {
      if (a.length !== b.length) return false;
      for (let i = 0; i < a.length; i++) if (!equal(a[i], b[i])) return false;
      return true;
    }
    const keys = Object.keys(a);
    if (keys.length !== Object.keys(b).length) return false;
    for (const k of keys) if (!Object.prototype.hasOwnProperty.call(b, k) || !equal(a[k], b[k])) return false;
    return true;
  }
  return a !== a && b !== b;
}`;

function validatorSource(schema: JsonObject): string {
  // The same options floorspec's own schema check uses (tools/schema.ts), except formats: in JSON
  // Schema 2020-12 `format` is an annotation, and the `pattern` beside the asset's `uri` is what
  // every validator checks (schema/core/README.md).
  const ajv = new Ajv2020({
    strict: true,
    strictRequired: false,
    allErrors: true,
    validateFormats: false,
    code: { source: true, esm: true, lines: true },
  });
  const validate = ajv.compile(schema);
  let code = standaloneCode(ajv, validate);
  const helpers: string[] = [];
  code = code.replace(/const (\w+) = require\("ajv\/dist\/runtime\/(\w+)"\)\.default;?/g, (_m, local: string, mod: string) => {
    if (mod === 'ucs2length') helpers.push(UCS2LENGTH.replace('function ucs2length', `function ${local}`));
    else if (mod === 'equal') helpers.push(EQUAL.replace(/equal\(/g, `${local}(`));
    else throw new Error(`standalone code requires ajv/dist/runtime/${mod}, which generate.ts does not inline`);
    return '';
  });
  if (/require\(/.test(code)) throw new Error('standalone code still requires a module');
  if (/new Function|eval\(/.test(code)) throw new Error('standalone code evaluates code at runtime');
  return (
    HEADER('The Core 0.1 schema tier (FS-SCH-001), compiled by ajv to standalone code: no code is evaluated at runtime.') +
    '// @ts-nocheck\n/* eslint-disable */\n' +
    helpers.join('\n') +
    '\n' +
    code.trim() +
    '\n'
  );
}

async function typesSource(schema: JsonObject): Promise<string> {
  const ts = await compile(structuredClone(schema), 'FloorspecDocument', {
    bannerComment: '',
    additionalProperties: false,
    unreachableDefinitions: false,
    strictIndexSignatures: true,
    format: true,
    style: { singleQuote: true, printWidth: 120 },
  });
  return HEADER('TypeScript types for a Core 0.1 document, generated from the schema with json-schema-to-typescript.') + '/* eslint-disable */\n' + ts;
}

export async function generate(): Promise<Map<string, string>> {
  const files = loadFiles();
  const bundled = bundle(files);
  const out = new Map<string, string>();
  out.set(
    'schema.ts',
    HEADER('The Core 0.1 schema files bundled into one schema. Its `default` keywords are the constant defaults of 9.2 step 1.') +
      `export const SCHEMA = ${JSON.stringify(bundled, null, 2)} as const;\n`,
  );
  out.set('validate.ts', validatorSource(bundled));
  out.set('types.ts', await typesSource(bundled));
  return out;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const out = await generate();
  let stale = 0;
  for (const [name, text] of out) {
    const path = join(outDir, name);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
    if (current === text) continue;
    if (check) {
      console.error(`check:generated: src/generated/${name} is out of date — run \`pnpm --filter @floorspec/engine generate\``);
      stale++;
    } else {
      writeFileSync(path, text);
      console.log(`generate: wrote src/generated/${name}`);
    }
  }
  if (stale) process.exit(1);
  if (check) console.log('check:generated: src/generated is up to date');
}

await main();
