"""Write requirements.lock and requirements-dev.lock from the exact pins in requirements*.in.

    python3 scripts/lock.py

Each pinned version gets the sha256 of every file PyPI publishes for it, so `pip install
--require-hashes` accepts whichever wheel fits the platform (macOS arm64 for development,
manylinux x86_64 or aarch64 in the image) and nothing else. A version published in the last
seven days is refused: most malicious releases are found and pulled inside that window.
"""

from __future__ import annotations

import datetime as dt
import json
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
MIN_AGE = dt.timedelta(days=7)


def pins(path: Path) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("-r "):
            out += pins(path.parent / line[3:].strip())
            continue
        if "==" not in line:
            sys.exit(f"{path.name}: {line} is not pinned exactly")
        name, version = line.split("==", 1)
        out.append((name.strip(), version.strip()))
    return out


def hashes(name: str, version: str) -> list[str]:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as r:
        data = json.load(r)
    files = data["urls"]
    if not files:
        sys.exit(f"{name}=={version} has no files on PyPI")
    published = min(dt.datetime.fromisoformat(f["upload_time_iso_8601"].replace("Z", "+00:00")) for f in files)
    if dt.datetime.now(dt.timezone.utc) - published < MIN_AGE:
        sys.exit(f"{name}=={version} was published {published:%Y-%m-%d}, less than seven days ago")
    if any(f.get("yanked") for f in files):
        sys.exit(f"{name}=={version} is yanked")
    return sorted({f["digests"]["sha256"] for f in files})


def write(source: str, target: str) -> None:
    lines = [f"# GENERATED by scripts/lock.py from {source} — do not edit; edit {source} and run it again.", ""]
    for name, version in sorted(pins(HERE / source), key=lambda p: p[0].lower()):
        hs = hashes(name, version)
        lines.append(f"{name}=={version} \\")
        lines += [f"    --hash=sha256:{h}" + (" \\" if i < len(hs) - 1 else "") for i, h in enumerate(hs)]
    (HERE / target).write_text("\n".join(lines) + "\n")
    print(f"{target}: {len(pins(HERE / source))} pins")


if __name__ == "__main__":
    write("requirements.in", "requirements.lock")
    write("requirements-dev.in", "requirements-dev.lock")
